baseurl = "https://vvelikodny.github.io/"
title = "Vitaly's Blog"
copyright = "Copyright &copy; 2018 - Vitaly Velikodny"
canonifyurls = true

disqusShortname = "vvelikodny"

theme = "kiera"
paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

publishDir = "docs"

[author]
    name = "Vitaly V."
    avatar = "/img/avatar.png"
    github = "vvelikodny"
    gitlab = "vvelikodny"
    linkedin = "vvelikodny"
    facebook = ""
    twitter = ""
    instagram = ""
    stackoverflow = "/1653085/vvelikodny"

[params]
    tagline = "Vitaly's Blog for Creative and Technical Writing"
    meta = "false"


