baseurl = "https://velikodny.com"
title = "Vitaly Velikodnyi - Senior Software Developer"
copyright = "Copyright &copy; 2020 - Vitaly Velikodny"
canonifyurls = true

disqusShortname = "vvelikodny"

theme = "kiera"
paginate = 5

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

publishDir = "docs"

[author]
    name = "Vitaly Velikodnyi"
    avatar = "/img/avatar3.jpg"
    github = "vvelikodny"
    gitlab = "vvelikodny"
    linkedin = "vvelikodny"
    facebook = "vvelikodny"
    twitter = "vvelikodny"
    instagram = ""
    stackoverflow = "/1653085/vvelikodny"
    email = "vvelikodny@gmail.com"

[params]
    tagline = "Vitaly Velikodnyi's Blog for Creative and Technical Writing"
    meta = "false"
    css = ["css/custom.css"]


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/"
    weight = -1

  [[menu.main]]
    identifier = "about-me"
    name = "About me"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about-me"
    weight = 100


[permalinks]
  posts = "/:year/:month/:day/:title/"